# Generated by Django 5.0 on 2023-12-10 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_bancaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_ingreso',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha Ingreso'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id_cuenta', models.AutoField(primary_key=True, serialize=False)),
                ('nro_contrato', models.CharField(blank=True, editable=False, max_length=255, unique=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Alta')),
                ('tipo_cuenta', models.CharField(choices=[('CUENTA CORRIENTE', 'CUENTA CORRIENTE'), ('CAJA DE AHORRO', 'CAJA DE AHORRO')])),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_mantenimiento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('promedio_acreditacion', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('moneda', models.CharField(choices=[('GS', 'GS'), ('USD', 'USD')], default='GS')),
                ('estado', models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO'), ('BLOQUEADO', 'BLOQUEADO')], default='ACTIVO')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='gestion_bancaria.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id_movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('tipo_movimiento', models.CharField(choices=[('CREDITO', 'CREDITO'), ('DEBITO', 'DEBITO')])),
                ('saldo_anterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_actual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_movimiento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cuenta_origen', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cuenta_destino', models.DecimalField(decimal_places=2, max_digits=10)),
                ('canal', models.CharField(choices=[('APP', 'APP'), ('WEB', 'WEB')], default='WEB')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta', to='gestion_bancaria.cuenta')),
            ],
        ),
    ]
